<?php
	$lang["system"]["debug_runtime"] = "[lang]_debug_runtime";
	$lang["system"]["debug_memory"] = "[lang]_debug_memory";
	$lang["system"]["debug_user_id"] = "[lang]_debug_user_id";
	$lang["system"]["debug_user_name"] = "[lang]_debug_user_name";
	$lang["system"]["guestuser"] = "[lang]_guestuser";
	$lang["system"]["welcome"] = "[lang]_welcome";
	$lang["system"]["register"] = "[lang]_register";
	$lang["system"]["login"] = "[lang]_login";
	$lang["system"]["profile"] = "[lang]_profile";
	$lang["system"]["logout"] = "[lang]_logout";
	$lang["system"]["et_tshirt"] = "[lang]_et_tshirt";
	$lang["system"]["admin"] = "[lang]_admin";
?>