<?php
	$lang["system"]["welcome"] = "[lang]_welcome";
	$lang["system"]["profile"] = "[lang]_profile";
	$lang["system"]["logout"] = "[lang]_logout";
	$lang["system"]["admin"] = "[lang]_admin";
	$lang["system"]["debug_runtime"] = "[lang]_debug_runtime";
	$lang["system"]["debug_memory"] = "[lang]_debug_memory";
	$lang["system"]["debug_user_id"] = "[lang]_debug_user_id";
	$lang["system"]["debug_user_name"] = "[lang]_debug_user_name";
	$lang["system"]["register"] = "[lang]_register";
	$lang["system"]["login"] = "[lang]_login";
	$lang["system"]["guestuser"] = "[lang]_guestuser";
	$lang["system"]["system_massages_title"] = "[lang]_system_massages_title";
	$lang["system"]["no_admin_user"] = "[lang]_no_admin_user";
	$lang["system"]["no_admin_add_user"] = "[lang]_no_admin_add_user";
	$lang["system"]["no_admin_delete_string"] = "[lang]_no_admin_delete_string";
	$lang["system"]["no_admin_securety_admin_challange"] = "[lang]_no_admin_securety_admin_challange";
	$lang["system"]["no_admin_user_desc"] = "[lang]_no_admin_user_desc";
	$lang["system"]["no_admin_challange_desc"] = "[lang]_no_admin_challange_desc";
	$lang["system"]["no_admin_challange_todo"] = "[lang]_no_admin_challange_todo";
	$lang["system"]["session_restart"] = "[lang]_session_restart";
?>