<?php
	$lang["admin.inc"]["mainerror_fnf_title"] = "[lang]_mainerror_fnf_title";
	$lang["admin.inc"]["mainerror_fnf_body"] = "[lang]_mainerror_fnf_body";
	$lang["admin.inc"]["not_a_admin"] = "[lang]_not_a_admin";
	$lang["admin.inc"]["admin_main_menue"] = "[lang]_admin_main_menue";
	$lang["admin.inc"]["menue_status"] = "[lang]_menue_status";
	$lang["admin.inc"]["menue_module"] = "[lang]_menue_module";
	$lang["admin.inc"]["admin_modul_menue"] = "[lang]_admin_modul_menue";
?>