<?php
	$lang["et_tshirt.inc"]["datenerfassung"] = "[lang]_datenerfassung";
	$lang["et_tshirt.inc"]["title_daten"] = "[lang]_title_daten";
	$lang["et_tshirt.inc"]["daten"] = "[lang]_daten";
	$lang["et_tshirt.inc"]["no_data_stored"] = "[lang]_no_data_stored";
	$lang["et_tshirt.inc"]["data_change"] = "[lang]_data_change";
	$lang["et_tshirt.inc"]["user_name"] = "[lang]_user_name";
	$lang["et_tshirt.inc"]["user_name_desc"] = "[lang]_user_name_desc";
	$lang["et_tshirt.inc"]["team"] = "[lang]_team";
	$lang["et_tshirt.inc"]["team_desc"] = "[lang]_team_desc";
	$lang["et_tshirt.inc"]["rang"] = "[lang]_rang";
	$lang["et_tshirt.inc"]["rang_desc"] = "[lang]_rang_desc";
	$lang["et_tshirt.inc"]["shelter_1"] = "[lang]_shelter_1";
	$lang["et_tshirt.inc"]["shelter_1_desc"] = "[lang]_shelter_1_desc";
	$lang["et_tshirt.inc"]["shelter_2"] = "[lang]_shelter_2";
	$lang["et_tshirt.inc"]["shelter_2_desc"] = "[lang]_shelter_2_desc";
	$lang["et_tshirt.inc"]["shelter_3"] = "[lang]_shelter_3";
	$lang["et_tshirt.inc"]["shelter_3_desc"] = "[lang]_shelter_3_desc";
	$lang["et_tshirt.inc"]["shelter_4"] = "[lang]_shelter_4";
	$lang["et_tshirt.inc"]["shelter_4_desc"] = "[lang]_shelter_4_desc";
	$lang["et_tshirt.inc"]["shelter_5"] = "[lang]_shelter_5";
	$lang["et_tshirt.inc"]["shelter_5_desc"] = "[lang]_shelter_5_desc";
	$lang["et_tshirt.inc"]["shelter_6"] = "[lang]_shelter_6";
	$lang["et_tshirt.inc"]["shelter_6_desc"] = "[lang]_shelter_6_desc";
	$lang["et_tshirt.inc"]["submit"] = "[lang]_submit";
	$lang["et_tshirt.inc"]["data_stored"] = "[lang]_data_stored";
	$lang["et_tshirt.inc"]["tilte_preview"] = "[lang]_tilte_preview";
	$lang["et_tshirt.inc"]["back_to_main"] = "[lang]_back_to_main";
	$lang["et_tshirt.inc"]["data_user: <tt>Siggi</tt><br>"] = "[lang]_data_user: <tt>Siggi</tt><br>";
	$lang["et_tshirt.inc"]["data_rang: <tt>Blutiger Anf&auml"] = "[lang]_data_rang: <tt>Blutiger Anf&auml";
	$lang["et_tshirt.inc"]["title_preview"] = "[lang]_title_preview";
	$lang["et_tshirt.inc"]["data_user: <tt>Siggi</tt><br><br><a href='./index.php&#63"] = "[lang]_data_user: <tt>Siggi</tt><br><br><a href='./index.php&#63";
	$lang["et_tshirt.inc"]["data_user: <tt>Monika</tt><br><br><a href='./index.php&#63"] = "[lang]_data_user: <tt>Monika</tt><br><br><a href='./index.php&#63";
	$lang["et_tshirt.inc"]["data_user: <tt>Dana</tt><br><br><a href='./index.php&#63"] = "[lang]_data_user: <tt>Dana</tt><br><br><a href='./index.php&#63";
	$lang["et_tshirt.inc"]["data_user: <tt>Michaela</tt><br><br><a href='./index.php&#63"] = "[lang]_data_user: <tt>Michaela</tt><br><br><a href='./index.php&#63";
	$lang["et_tshirt.inc"]["data_user"] = "[lang]_data_user";
	$lang["et_tshirt.inc"]["data_ID"] = "[lang]_data_ID";
	$lang["et_tshirt.inc"]["vorschau"] = "[lang]_vorschau";
	$lang["et_tshirt.inc"]["vorschau_desc"] = "[lang]_vorschau_desc";
	$lang["et_tshirt.inc"]["shop_title"] = "[lang]_shop_title";
	$lang["et_tshirt.inc"]["shop_desc"] = "[lang]_shop_desc";
	$lang["et_tshirt.inc"]["admin_options:<a href='./index.php&#63"] = "[lang]_admin_options:<a href='./index.php&#63";
	$lang["et_tshirt.inc"]["admin_options:<br><a href='./index.php&#63"] = "[lang]_admin_options:<br><a href='./index.php&#63";
	$lang["et_tshirt.inc"]["list_of_products"] = "[lang]_list_of_products";
	$lang["et_tshirt.inc"]["admin_pd_detail"] = "[lang]_admin_pd_detail";
	$lang["et_tshirt.inc"]["admin_pd_raw"] = "[lang]_admin_pd_raw";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td>Organic Shirt</td>
  <tr><td>"] = "[lang]_admin_pd_name</td><td>Organic Shirt</td>
  <tr><td>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td>Herren T-Shirt, rundhals, 180g/m², 100% ringgesponnene Bio-Baumwolle</td>
  <tr><td>"] = "[lang]_admin_pd_desc</td><td>Herren T-Shirt, rundhals, 180g/m², 100% ringgesponnene Bio-Baumwolle</td>
  <tr><td>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td><ul>
<li>100% gekämmte, ringgesponnene Bio-Baumwolle</li>
<li>Grammatur: 180g/m²</li>
<li>Eingesetzte Ärmel</li>
<li>Single Jersey</li>
</ul></td>
  <tr><td>"] = "[lang]_admin_pd_desc_detail</td><td><ul>
<li>100% gekämmte, ringgesponnene Bio-Baumwolle</li>
<li>Grammatur: 180g/m²</li>
<li>Eingesetzte Ärmel</li>
<li>Single Jersey</li>
</ul></td>
  <tr><td>";
	$lang["et_tshirt.inc"]["admin_pd_pic </td><td><img src='' /></td>
  <tr><td>"] = "[lang]_admin_pd_pic </td><td><img src='' /></td>
  <tr><td>";
	$lang["et_tshirt.inc"]["admin_pd_cath</td><td><tt>ID: <b>1</b></tt> - Unisex-Shirts</td>
</table>
<br /><br />"] = "[lang]_admin_pd_cath</td><td><tt>ID: <b>1</b></tt> - Unisex-Shirts</td>
</table>
<br /><br />";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td><img src='https://www.shirtigo.de/images/produkte/290/organic_shirt_new.jpg' /></td>
  <tr><td>"] = "[lang]_admin_pd_pic 1</td><td><img src='https://www.shirtigo.de/images/produkte/290/organic_shirt_new.jpg' /></td>
  <tr><td>";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td id='templ_table_right'>Organic Shirt</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_name</td><td id='templ_table_right'>Organic Shirt</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td id='templ_table_right'>Herren T-Shirt, rundhals, 180g/m², 100% ringgesponnene Bio-Baumwolle</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc</td><td id='templ_table_right'>Herren T-Shirt, rundhals, 180g/m², 100% ringgesponnene Bio-Baumwolle</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>100% gekämmte, ringgesponnene Bio-Baumwolle</li>
<li>Grammatur: 180g/m²</li>
<li>Eingesetzte Ärmel</li>
<li>Single Jersey</li>
</ul></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>100% gekämmte, ringgesponnene Bio-Baumwolle</li>
<li>Grammatur: 180g/m²</li>
<li>Eingesetzte Ärmel</li>
<li>Single Jersey</li>
</ul></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/organic_shirt_new.jpg' /></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/organic_shirt_new.jpg' /></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_cath</td><td id='templ_table_right'><tt>ID: <b>1</b></tt> - Unisex-Shirts</td>
</table>
<br /><br />"] = "[lang]_admin_pd_cath</td><td id='templ_table_right'><tt>ID: <b>1</b></tt> - Unisex-Shirts</td>
</table>
<br /><br />";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><br><ul>
<li>100% gekämmte, ringgesponnene Bio-Baumwolle</li>
<li>Grammatur: 180g/m²</li>
<li>Eingesetzte Ärmel</li>
<li>Single Jersey</li>
</ul></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><br><ul>
<li>100% gekämmte, ringgesponnene Bio-Baumwolle</li>
<li>Grammatur: 180g/m²</li>
<li>Eingesetzte Ärmel</li>
<li>Single Jersey</li>
</ul></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_is_activ</td><td id='templ_table_right'><font color='green'>verfügbar</font></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_is_activ</td><td id='templ_table_right'><font color='green'>verfügbar</font></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_manufacturer</td><td id='templ_table_right'>Stanley & Stella</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_manufacturer</td><td id='templ_table_right'>Stanley & Stella</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=50>325-&gt"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=50>325-&gt";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=70>325-&gt"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=70>325-&gt";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=100>325-&gt"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=100>325-&gt";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=150>325-&gt"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=150>325-&gt";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=150>325 -&gt"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=150>325 -&gt";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=200>325 -&gt"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=200>325 -&gt";
	$lang["et_tshirt.inc"]["admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_organic_shirt.png' /></td>
</table>
<br /><br />"] = "[lang]_admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_organic_shirt.png' /></td>
</table>
<br /><br />";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#F8F8F8'>&nbsp"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#F8F8F8'>&nbsp";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td id='templ_table_right'>Organic Tote-Bag</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_name</td><td id='templ_table_right'>Organic Tote-Bag</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td id='templ_table_right'>Tasche, Größe ca. 38x42 cm, 300 g/m², 80% recycelte Baumwolle und 20% recyceltes Polyester</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc</td><td id='templ_table_right'>Tasche, Größe ca. 38x42 cm, 300 g/m², 80% recycelte Baumwolle und 20% recyceltes Polyester</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Tasche aus&nbsp"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Tasche aus&nbsp";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#F4EAD0'>&nbsp"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#F4EAD0'>&nbsp";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/totebag.jpg' /></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/totebag.jpg' /></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_size_chart</td><td id='templ_table_right'><img src='' /></td>
</table>
<br /><br />"] = "[lang]_admin_pd_size_chart</td><td id='templ_table_right'><img src='' /></td>
</table>
<br /><br />";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td id='templ_table_right'>Organic Gym-Bag</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_name</td><td id='templ_table_right'>Organic Gym-Bag</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td id='templ_table_right'>Größe ca. 38x42cm, 300g/m², 80% recycelte Baumwolle, 20% recyceltes Polyester</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc</td><td id='templ_table_right'>Größe ca. 38x42cm, 300g/m², 80% recycelte Baumwolle, 20% recyceltes Polyester</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>80% recycelte Baumwolle, 20% recyceltes Polyester</li>
<li>Schwere Zugkordeln mit Knoten und Metallbesatz an den Enden</li>
<li>Graumetallösen</li>
<li>Dreieckverstärkungen an den unteren Ecken</li>
<li>Heavy canvas, 300 g/m²</li>
<li>Größe ca. 38x42 cm</li>
</ul></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>80% recycelte Baumwolle, 20% recyceltes Polyester</li>
<li>Schwere Zugkordeln mit Knoten und Metallbesatz an den Enden</li>
<li>Graumetallösen</li>
<li>Dreieckverstärkungen an den unteren Ecken</li>
<li>Heavy canvas, 300 g/m²</li>
<li>Größe ca. 38x42 cm</li>
</ul></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/organic_gymbag.jpg' /></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/organic_gymbag.jpg' /></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td id='templ_table_right'>Baumwolltasche</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_name</td><td id='templ_table_right'>Baumwolltasche</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td id='templ_table_right'>Tasche, Größe ca. 38x42 cm, Henkellänge ca. 69 cm, 140 g/m², 100% Baumwolle</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc</td><td id='templ_table_right'>Tasche, Größe ca. 38x42 cm, Henkellänge ca. 69 cm, 140 g/m², 100% Baumwolle</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>100% Baumwolle</li>
<li>Grammatur: 140g/qm</li>
<li>Volumen ca. 10 Liter</li>
<li>Henkellänge ca. 69 cm</li>
</ul></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>100% Baumwolle</li>
<li>Grammatur: 140g/qm</li>
<li>Volumen ca. 10 Liter</li>
<li>Henkellänge ca. 69 cm</li>
</ul></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_manufacturer</td><td id='templ_table_right'>Westford Mill</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_manufacturer</td><td id='templ_table_right'>Westford Mill</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/westford_mill_premium_baumwolltasche_langer_henkel.jpg' /></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/westford_mill_premium_baumwolltasche_langer_henkel.jpg' /></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_price</td><td id='templ_table_right'>(color) -&gt"] = "[lang]_admin_pd_price</td><td id='templ_table_right'>(color) -&gt";
	$lang["et_tshirt.inc"]["admin_pd_price</td><td id='templ_table_right'>(white) -&gt"] = "[lang]_admin_pd_price</td><td id='templ_table_right'>(white) -&gt";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td id='templ_table_right'>Premium Shirt</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_name</td><td id='templ_table_right'>Premium Shirt</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td id='templ_table_right'>Unisex T-Shirt, rundhals, 185g/m², 100% ringgesponnene Baumwolle</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc</td><td id='templ_table_right'>Unisex T-Shirt, rundhals, 185g/m², 100% ringgesponnene Baumwolle</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Kurzarm T-Shirt, Medium Fit</li>
<li>Rundhalsausschnitt in 1x1-Rippstrick</li>
<li>100% ringgesponnene Baumwolle (Sport Grey: 85% Baumwolle, 15% Viskose"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Kurzarm T-Shirt, Medium Fit</li>
<li>Rundhalsausschnitt in 1x1-Rippstrick</li>
<li>100% ringgesponnene Baumwolle (Sport Grey: 85% Baumwolle, 15% Viskose";
	$lang["et_tshirt.inc"]["admin_pd_manufacturer</td><td id='templ_table_right'>B&C Europeanstyle</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_manufacturer</td><td id='templ_table_right'>B&C Europeanstyle</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#272727'>&nbsp"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#272727'>&nbsp";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/new_premium_shirt_men_1.jpg' /></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/new_premium_shirt_men_1.jpg' /></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_premium_shirt.png' /></td>
</table>
<br /><br />"] = "[lang]_admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_premium_shirt.png' /></td>
</table>
<br /><br />";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td id='templ_table_right'>Ladies Premium Shirt</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_name</td><td id='templ_table_right'>Ladies Premium Shirt</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td id='templ_table_right'>Damen T-Shirt, rundhals, 185g/m², 100% ringgesponnene Baumwolle</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc</td><td id='templ_table_right'>Damen T-Shirt, rundhals, 185g/m², 100% ringgesponnene Baumwolle</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Kurzarm T-Shirt mit&nbsp"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Kurzarm T-Shirt mit&nbsp";
	$lang["et_tshirt.inc"]["admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#00A0C8'>&nbsp"] = "[lang]_admin_pd_color</td><td id='templ_table_right'>
     <table>
     <tr>
       <td width=20 bgcolor='#00A0C8'>&nbsp";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/new_premium_shirt_ladies.jpg' /></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/new_premium_shirt_ladies.jpg' /></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_ladies_premium_shirt.png' /></td>
</table>
<br /><br />"] = "[lang]_admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_ladies_premium_shirt.png' /></td>
</table>
<br /><br />";
	$lang["et_tshirt.inc"]["admin_pd_name</td><td id='templ_table_right'>Classic Shirt</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_name</td><td id='templ_table_right'>Classic Shirt</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc</td><td id='templ_table_right'>no description available</td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_desc</td><td id='templ_table_right'>no description available</td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Kurzarm T-Shirt,&nbsp"] = "[lang]_admin_pd_desc_detail</td><td id='templ_table_right'><ul>
<li>Kurzarm T-Shirt,&nbsp";
	$lang["et_tshirt.inc"]["admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/new_classic_shirt_men.jpg' /></td>
  <tr><td id='templ_table_left'>"] = "[lang]_admin_pd_pic 1</td><td id='templ_table_right'><img src='https://www.shirtigo.de/images/produkte/290/new_classic_shirt_men.jpg' /></td>
  <tr><td id='templ_table_left'>";
	$lang["et_tshirt.inc"]["admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_classic_shirt.png' /></td>
</table>
<br /><br />"] = "[lang]_admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_classic_shirt.png' /></td>
</table>
<br /><br />";
	$lang["et_tshirt.inc"]["admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_organic_shirt.png' /></td>
</table>
</table>
<br><br><a href='./index.php&#63"] = "[lang]_admin_pd_size_chart</td><td id='templ_table_right'><img src='https://s3-eu-west-1.amazonaws.com/shirtigo-assets/sizecharts/size_chart_organic_shirt.png' /></td>
</table>
</table>
<br><br><a href='./index.php&#63";
	$lang["et_tshirt.inc"]["new_product"] = "[lang]_new_product";
?>