<?php
	$lang["fnf.inc"]["linkerror_cidnf_title"] = "[lang]_linkerror_cidnf_title";
	$lang["fnf.inc"]["linkerror_cidnf_body"] = "[lang]_linkerror_cidnf_body";
	$lang["fnf.inc"]["register_windows_title"] = "[lang]_register_windows_title";
	$lang["fnf.inc"]["welcome_new_user.</div></div>

		

			<div style='width: 100%"] = "[lang]_welcome_new_user.</div></div>

		

			<div style='width: 100%";
	$lang["fnf.inc"]["logout"] = "[lang]_logout";
	$lang["fnf.inc"]["login"] = "[lang]_login";
	$lang["fnf.inc"]["login_windows"] = "[lang]_login_windows";
	$lang["fnf.inc"]["user_name"] = "[lang]_user_name";
	$lang["fnf.inc"]["user_pass"] = "[lang]_user_pass";
	$lang["fnf.inc"]["submit"] = "[lang]_submit";
	$lang["fnf.inc"]["welcome_login"] = "[lang]_welcome_login";
	$lang["fnf.inc"]["welcome_new_user.</div></div>

			

			<br><br><br><br>

			<div id='templ_foot'>EGS - Prüfungsdatenbank - 0.01 &nbsp"] = "[lang]_welcome_new_user.</div></div>

			

			<br><br><br><br>

			<div id='templ_foot'>EGS - Prüfungsdatenbank - 0.01 &nbsp";
	$lang["fnf.inc"]["login</div><div id='templ_window_box'>"] = "[lang]_login</div><div id='templ_window_box'>";
?>