<?php
	$lang["login.inc"]["login_windows 

<form action='./&#63"] = "[lang]_login_windows 

<form action='./&#63";
	$lang["login.inc"]["user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='AFP5zkiE' /></td></tr>
<tr><td id='form_table_right'>"] = "[lang]_user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='AFP5zkiE' /></td></tr>
<tr><td id='form_table_right'>";
	$lang["login.inc"]["user_name_desc</td></tr>
<tr><td id='form_table_right_error'><ul id='form_table_error_ul'><li>"] = "[lang]_user_name_desc</td></tr>
<tr><td id='form_table_right_error'><ul id='form_table_error_ul'><li>";
	$lang["login.inc"]["user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='BDTb1Wol' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='gultvYZ1' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='L7eCeDc5' value='Einloggen &gt"] = "[lang]_user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='BDTb1Wol' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='gultvYZ1' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='L7eCeDc5' value='Einloggen &gt";
	$lang["login.inc"]["user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='NZglklmn' /></td></tr>
<tr><td id='form_table_right'>"] = "[lang]_user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='NZglklmn' /></td></tr>
<tr><td id='form_table_right'>";
	$lang["login.inc"]["user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='gwUeEjA6' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='ocb4r3ad' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='Iy91VWYy' value='Einloggen &gt"] = "[lang]_user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='gwUeEjA6' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='ocb4r3ad' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='Iy91VWYy' value='Einloggen &gt";
	$lang["login.inc"]["user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='oH5WLkUn' /></td></tr>
<tr><td id='form_table_right'>"] = "[lang]_user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='oH5WLkUn' /></td></tr>
<tr><td id='form_table_right'>";
	$lang["login.inc"]["user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='a8Al5v3F' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='bMkwvNXv' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='qXgnTfkm' value='Einloggen &gt"] = "[lang]_user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='a8Al5v3F' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='bMkwvNXv' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='qXgnTfkm' value='Einloggen &gt";
	$lang["login.inc"]["user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='U52H5Pkr' /></td></tr>
<tr><td id='form_table_right'>"] = "[lang]_user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='U52H5Pkr' /></td></tr>
<tr><td id='form_table_right'>";
	$lang["login.inc"]["user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='Mx4f7B6E' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='mOxoCDpT' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='KDp4ytC7' value='Einloggen &gt"] = "[lang]_user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='Mx4f7B6E' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='mOxoCDpT' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='KDp4ytC7' value='Einloggen &gt";
	$lang["login.inc"]["user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='DS0qcQmJ' /></td></tr>
<tr><td id='form_table_right'>"] = "[lang]_user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='DS0qcQmJ' /></td></tr>
<tr><td id='form_table_right'>";
	$lang["login.inc"]["user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='wJrEKhhX' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='N1wO460R' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='DZaS30fF' value='Einloggen &gt"] = "[lang]_user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='wJrEKhhX' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='N1wO460R' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='DZaS30fF' value='Einloggen &gt";
	$lang["login.inc"]["user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='NrnKacUG' /></td></tr>
<tr><td id='form_table_right'>"] = "[lang]_user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='NrnKacUG' /></td></tr>
<tr><td id='form_table_right'>";
	$lang["login.inc"]["user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='t1AaNROB' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='bAWme4JO' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='HyKeaflQ' value='Einloggen &gt"] = "[lang]_user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='t1AaNROB' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='bAWme4JO' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='HyKeaflQ' value='Einloggen &gt";
	$lang["login.inc"]["user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='OAs8twK5' /></td></tr>
<tr><td id='form_table_right'>"] = "[lang]_user_name</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='OAs8twK5' /></td></tr>
<tr><td id='form_table_right'>";
	$lang["login.inc"]["user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='mlq5bJDX' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='DuF7eqQz' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='cm1OV0QE' value='Einloggen &gt"] = "[lang]_user_name_error_1</li><li>Der Benutzername ist nicht lang genug.</li><li>Der Name ist nicht vergeben.</li></ul></td></tr>
<tr><td id='form_table_right'>Das hier ist ein Kommentar</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Benutzername 2</td><td id='form_table_right'><input type='text' id='form_table_input_default' name='mlq5bJDX' /></td></tr>
<tr><td id='form_table_right'>Bitte gib deinen Benutzername ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left' rowspan=2>Passworteingabe</td><td id='form_table_right'><input type='password' id='form_table_input_default' name='DuF7eqQz' /></td></tr>
      <tr><td id='form_table_right'>Bitte gib dein Passwort ein.</td></tr>
    <tr id='form_table_top_tr'><td id='form_table_left_submit' colspan='2'><input type='submit' id='form_table_submit_default' name='cm1OV0QE' value='Einloggen &gt";
	$lang["login.inc"]["login"] = "[lang]_login";
	$lang["login.inc"]["login_windows"] = "[lang]_login_windows";
	$lang["login.inc"]["user_name"] = "[lang]_user_name";
	$lang["login.inc"]["user_pass"] = "[lang]_user_pass";
	$lang["login.inc"]["submit"] = "[lang]_submit";
	$lang["login.inc"]["user_pass_wrong"] = "[lang]_user_pass_wrong";
?>