<?php
	$lang["register.inc"]["greeting"] = "[lang]_greeting";
	$lang["register.inc"]["user_name"] = "[lang]_user_name";
	$lang["register.inc"]["username_to_short"] = "[lang]_username_to_short";
	$lang["register.inc"]["username_fist_must_not__"] = "[lang]_username_fist_must_not__";
	$lang["register.inc"]["password"] = "[lang]_password";
	$lang["register.inc"]["password_desc"] = "[lang]_password_desc";
	$lang["register.inc"]["password_to_short"] = "[lang]_password_to_short";
	$lang["register.inc"]["password_does_not_match"] = "[lang]_password_does_not_match";
	$lang["register.inc"]["password_repeat"] = "[lang]_password_repeat";
	$lang["register.inc"]["email"] = "[lang]_email";
	$lang["register.inc"]["email_to_short"] = "[lang]_email_to_short";
	$lang["register.inc"]["submit"] = "[lang]_submit";
	$lang["register.inc"]["register_windows_title"] = "[lang]_register_windows_title";
?>