<?php
	
	$config = array();

	$config["main"]["projectname"] 	= "EGS - Prüfungsdatenbank";
	$config["main"]["version"] 		= "0.01";
	$config["main"]["index"]		= "index.php";
	$config["main"]["start_cid"]	= 1;
	
	$config["db"]["host"]			= "localhost";
	$config["db"]["user"]			= "raspberry";
	$config["db"]["pass"]			= "pipi";
	$config["db"]["db"]				= "powerbb_001";
	$config["db"]["prefix"]			= "pbb_";
	
	//$config["user"]["add_admin_challange"] = "M6O1HCdtHeKBFNGnt/s2xZKVc1oy2up8lwaZhGltrYHA";
?>